[package]
name = "rusty-bundler"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
swc = { git = "https://github.com/swc-project/swc.git", optional = true}
anyhow = "1.0"
walkdir = "2.4"
